sources: ["M", "I", "E"]
source_parameters:
  - source: "E"
    parameter: ["choose", ["individual_liability", "1group1gene"]]

weights:
  - kind: "exonpart"
    malus: ["beta", 8.0, 1.0]
    local_malus: ["beta", 6, 1]
  - kind: "intron"
    malus: ["uniform", 0.5, 1.0]
    bonus: ["uniform", 1.0, 10]


source_weights:
  - kind: "intron"
    source: "I"
    weight: ["expuniform", 10, 0, 20]
  - kind: "intron"
    source: "E"
    weight: ["expuniform", 10, 0, 20]
  - kind: "intronpart"
    source: "I"
    boundaries: ["seq", 4, ["range", 1, 10]]
    weights: ["sample", 5, ["chi", 1, 1, 1]]
  - kind: "exon"
    source: "E"
    weight: ["expuniform", 10, 0, 20]
  - kind: "exonpart"
    source: "E"
    weight: ["gamma", 1, 1, 30]
  - kind: "ass"
    source: "I"
    boundaries: [1, 6, 12]
    weights: [1, ["uniform", 1.01, 2.99], ["uniform", 3.0, 9.99], 10]
