sources: ["M", "I", "E", "T", "P", "RM"]
source_parameters:
  - source: "E"
    parameter: ["choose", ["individual_liability", "1group1gene"]]
  - source: "P"
    parameter: ["choose", ["individual_liability", "1group1gene"]]
  - source: "R"
    parameter: ["choose", ["individual_liability", "1group1gene"]]

weights:
  - kind: "exonpart"
    malus: ["trunc", 0.1, 1.0, ["beta", 12.0, 1.0]]
    local_malus: ["trunc", 0.1, 1.0, ["beta", 10.0, 1.5]]
  - kind: "CDSpart"
    malus: ["trunc", 0.1, 1.0, ["beta", 12.0, 1.0]]
    local_malus: ["trunc", 0.1, 1.0, ["beta", 10.0, 1.5]]
  - kind: "UTRpart"
    malus: ["trunc", 0.1, 1.0, ["beta", 12.0, 1.0]]
    local_malus: ["trunc", 0.1, 1.0, ["beta", 10.0, 1.5]]
  - kind: "ass"
    malus: ["trunc", 0.1, 1.0, ["beta", 30.0, 1.0]]
    local_malus: ["trunc", 0.05, 1.0, ["beta", 3.0, 2.0]]
  - kind: "dss"
    malus: ["trunc", 0.1, 1.0, ["beta", 30.0, 1.0]]
    local_malus: ["trunc", 0.05, 1.0, ["beta", 3.0, 2.0]]
  - kind: "intron"
    malus: ["trunc", 0.1, 1.0, ["beta", 6.0, 1.0]]
  - kind: "start"
    malus: ["trunc", 0.1, 1.0, ["beta", 6.0, 1.0]]
  - kind: "stop"
    malus: ["trunc", 0.1, 1.0, ["beta", 6.0, 1.0]]


source_weights:
  - kind: "intron"
    source: "I"
    weight: ["expuniform", 10, 0, 20]
  - kind: "intron"
    source: "E"
    weight: ["expuniform", 10, 0, 20]
  - kind: "intron"
    source: "P"
    weight: ["expuniform", 10, 0, 20]
  - kind: "exonpart"
    source: "E"
    weight: ["gamma", 1.5, 1, 100]
  - kind: "CDSpart"
    source: "P"
    weight: ["gamma", 1.5, 1, 100]
  - kind: "CDSpart"
    source: "T"
    weight: ["gamma", 1.5, 1, 100]
  - kind: "ass"
    source: "I"
    weight: ["expuniform", 10, 0, 10]
  - kind: "dss"
    source: "I"
    weight: ["expuniform", 10, 0, 10]
  - kind: "ass"
    source: "E"
    weight: ["expuniform", 10, 0, 10]
  - kind: "dss"
    source: "E"
    weight: ["expuniform", 10, 0, 10]
  - kind: "nonexonpart"
    source: "RM"
    weight: ["chi", 1, 1, 2]
